name: dada_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.12.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  firebase_core: ^4.14.0
  cloud_firestore: ^6.9.0
  firebase_auth: ^6.6.1
  provider: ^6.1.5+1
  table_calendar: ^3.2.1
  intl: ^0.20.3
  add_2_calendar: ^3.1.1
  url_launcher: ^6.3.2
  image_picker: ^1.2.3
  file_picker: ^12.1.2
  firebase_storage: ^13.5.0
  path: ^1.9.1
  shared_preferences: ^2.5.5
  flutter_localizations:
    sdk: flutter
  google_fonts: ^8.2.1
  http: ^1.6.0
  flutter_widget_from_html: ^0.17.3
  flutter_quill: ^11.5.1
  vsc_quill_delta_to_html: ^1.0.5
  flutter_quill_delta_from_html: ^1.5.3
  razorpay_flutter: ^1.4.5
  cloud_functions: ^6.4.0
  connectivity_plus: ^7.3.1
  cached_network_image: ^4.0.0
  pdf: ^3.11.1
  printing: ^5.13.2
  share_plus: ^13.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

l10n_config:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-class: AppLocalizations

analysis_options_config:
  analyzer:
    exclude:
      - build/**
  include: package:flutter_lints/flutter.yaml
  linter:
    rules:
