// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALnxzTkO-9eRjBKWpUBV7T78CAjvkSGFw',
    appId: '1:683270494670:web:168d22dd418e8c31d2339f',
    messagingSenderId: '683270494670',
    projectId: 'dada-89661',
    authDomain: 'dada-89661.firebaseapp.com',
    storageBucket: 'dada-89661.firebasestorage.app',
    measurementId: 'G-WF57CEV09W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC01HYnauRmcGRT8OwWat8J5UO6dPHH7vI',
    appId: '1:683270494670:android:5cdfc322deaffbe7d2339f',
    messagingSenderId: '683270494670',
    projectId: 'dada-89661',
    storageBucket: 'dada-89661.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN_-HSv4_W-seZo_6ZoqJljSBJn4Ptu8M',
    appId: '1:683270494670:ios:f88d19691c4e7058d2339f',
    messagingSenderId: '683270494670',
    projectId: 'dada-89661',
    storageBucket: 'dada-89661.firebasestorage.app',
    iosClientId: '683270494670-05jkk4ul0k9in9k3k08hv0mgj4mghp36.apps.googleusercontent.com',
    iosBundleId: 'com.example.dada2',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN_-HSv4_W-seZo_6ZoqJljSBJn4Ptu8M',
    appId: '1:683270494670:ios:f88d19691c4e7058d2339f',
    messagingSenderId: '683270494670',
    projectId: 'dada-89661',
    storageBucket: 'dada-89661.firebasestorage.app',
    iosClientId: '683270494670-05jkk4ul0k9in9k3k08hv0mgj4mghp36.apps.googleusercontent.com',
    iosBundleId: 'com.example.dada2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALnxzTkO-9eRjBKWpUBV7T78CAjvkSGFw',
    appId: '1:683270494670:web:2c795b291b6ad309d2339f',
    messagingSenderId: '683270494670',
    projectId: 'dada-89661',
    authDomain: 'dada-89661.firebaseapp.com',
    storageBucket: 'dada-89661.firebasestorage.app',
    measurementId: 'G-Q6T2B8JGBZ',
  );
}
